### ISSUE TITLE
new features?

### ISSUE THREAD

**Issue by fantapop** [dragon3/Plack-App-GitSmartHttp#2]
Greetings!

Your project was selected to be a part of the cpan pull request challenge.  
http://blogs.perl.org/users/neilb/2014/12/take-the-2015-cpan-pull-request-challenge.html

I've reviewed your project and plack and the git Smart Http Protocol a little bit.  I'm wondering if there's anything you might have in mind for where you'd like to take your project next.

Here are a couple of ideas:
* Implement the http.getanyfile service as describe here http://git-scm.com/docs/git-http-backend.  Correct me if I'm wrong but it looks like Plack::App::GitSmartHttp doesn't currently implement this.
* Could do some performance profiling and try to make some small tweaks for efficiency.  From the sounds of it most of the time taken should be sending data across the wire so there may not be much that can be done.
* Could add tests.  It looks like you already have a fairly extensive set of tests.  Do you know of any area that's lacking?

**Comment by dragon3** [comment]
Hi @fantapop !
Sorry for the late reply.

Thank you for your suggestion!

>* Implement the http.getanyfile service as describe here http://git-scm.com/docs/git-http-backend.  Correct me if I'm wrong but it looks like Plack::App::GitSmartHttp doesn't currently implement this.

You are right.
Currently Plack::App::GitSmartHttp doesn't support "http.getanyfile", so I want to implement it.

>* Could do some performance profiling and try to make some small tweaks for efficiency.  From the sounds of it most of the time taken should be sending data across the wire so there may not be much that can be done.

I want to improve performance, but currently I have no idea.
Please let me know if you have any idea.

>* Could add tests.  It looks like you already have a fairly extensive set of tests.  Do you know of any area that's lacking?

Hmm... I think I have enough tests for current functions.

**Comment by fantapop** [comment]
Hey! okay I'm back now.  I just got the http-backend set up that ships with git.  I'll experiment with the http.getanyfile.  Another suggestion that was suggested by Neil Bower is to add the perl_version variable to the meta.yml file to add a check to your cpants page: http://cpants.cpanauthors.org/author/YAMAMOTO

it looks like that file is generated by something or other though.  It was unclear as to whether adding the version there would be beneficial.

**Comment by fantapop** [comment]
The more I look at this, the more it seems pretty pointless to implement that part of the spec.  I can't even find the version of git old enough to test it.

**Comment by dragon3** [comment]
@fantapop The version is described here:

**Comment by dragon3** [comment]
@fantapop

**Comment by dragon3** [comment]
@fantapop 
The version is described bellow:

http://git-scm.com/docs/git-http-backend#_services
> This serves Git clients older than version 1.6.6 ...

so you can test with this version, 
or I think you can make test cases like tests for `git-http-backend`:
https://github.com/git/git/blob/master/t/t556x_common

**Comment by fantapop** [comment]
What I mean is that version 1.6.6 of git is so old you can't even download
it anymore so this feature would never be used.  Maybe its better to add
some authentication for http.receivepack

**Comment by dragon3** [comment]
@fantapop 

> What I mean is that version 1.6.6 of git is so old you can't even download it anymore so this feature would never be used. 

Oh, sorry. I misunderstood, but I got it.
I agree with you, but if you want to implement it, I will assist you.

> Maybe its better to add some authentication for http.receivepack

Do you mean something like "Basic Authentication"?
If so, I don't want to add that, because authentication/authorization should be provided from other Plack::Middleware ( e.g. Plack::Middleware::Auth::* )

**Comment by dragon3** [comment]
Hi, @fantapop 

Do you have any update?
I will close this issue, but please let me know if you have something.

Thanks!
